# Retail Sales Forecasting and Business Intelligence using Machine Learning

## Phase 3 : Data Preprocessing & Feature Engineering

### Business Problem

Before building machine learning models, the raw dataset must be cleaned and transformed into a format suitable for training.

### Objectives

- Prepare clean data
- Engineer meaningful features
- Handle outliers
- Select relevant variables
- Prepare dataset for machine learning

1. Business Problem
2. Objectives
3. Import Libraries
4. Load Dataset
5. Data Cleaning
6. Feature Engineering
7. Outlier Analysis
8. Feature Selection
9. Data Scaling
10. Train-Test Split
11. Preprocessing Summary

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("/content/Walmart.csv")

In [4]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

In [5]:
df["Year"] = df["Date"].dt.year

df["Month"] = df["Date"].dt.month

df["Week"] = df["Date"].dt.isocalendar().week.astype(int)

df["Quarter"] = df["Date"].dt.quarter

In [7]:
df = df.drop("Date", axis=1)

In [8]:
df.isnull().sum()

Store           0
Weekly_Sales    0
Holiday_Flag    0
Temperature     0
Fuel_Price      0
CPI             0
Unemployment    0
Year            0
Month           0
Week            0
Quarter         0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Weekly_Sales  6435 non-null   float64
 2   Holiday_Flag  6435 non-null   int64
 3   Temperature   6435 non-null   float64
 4   Fuel_Price    6435 non-null   float64
 5   CPI           6435 non-null   float64
 6   Unemployment  6435 non-null   float64
 7   Year          6435 non-null   int32
 8   Month         6435 non-null   int32
 9   Week          6435 non-null   int64
 10  Quarter       6435 non-null   int32
dtypes: float64(5), int32(3), int64(3)
memory usage: 477.7 KB

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         6435 non-null   int64
 1   Weekly_Sales  6435 non-null   float64
 2   Holiday_Flag  6435 non-null   int64
 3   Temperature   6435 non-null   float64
 4   Fuel_Price    6435 non-null   float64
 5   CPI           6435 non-null   float64
 6   Unemployment  6435 non-null   float64
 7   Year          6435 non-null   int32
 8   Month         6435 non-null   int32
 9   Week          6435 non-null   int64
 10  Quarter       6435 non-null   int32
dtypes: float64(5), int32(3), int64(3)
memory usage: 477.7 KB

In [13]:
df.head()

,Store,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment,Year,Month,Week,Quarter
0,1,1643690.90,0,42.31,2.572,211.096358,8.106,2010,2,5,1
1,1,1641957.44,1,38.51,2.548,211.242170,8.106,2010,2,6,1
2,1,1611968.17,0,39.93,2.514,211.289143,8.106,2010,2,7,1
3,1,1409727.59,0,46.63,2.561,211.319643,8.106,2010,2,8,1
4,1,1554806.68,0,46.50,2.625,211.350143,8.106,2010,3,9,1

In [12]:
corr = df.corr(numeric_only=True)

corr["Weekly_Sales"].sort_values(ascending=False)

Weekly_Sales    1.000000
Month           0.076143
Week            0.074211
Quarter         0.063363
Holiday_Flag    0.036891
Fuel_Price      0.009464
Year           -0.018378
Temperature    -0.063810
CPI            -0.072634
Unemployment   -0.106176
Store          -0.335332
Name: Weekly_Sales, dtype: float64

## Observation

This analysis identifies which features have stronger relationships with Weekly Sales and helps us select useful predictors.

In [14]:
X = df.drop("Weekly_Sales", axis=1)

y = df["Weekly_Sales"]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [20]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

# Preprocessing Summary

- Converted Date into meaningful time-based features.
- Removed the original Date column.
- Verified data quality.
- Prepared feature and target variables.
- Split the dataset into training and testing sets.
- Standardized numerical features for machine learning.